#!/usr/bin/env python
import json
import sys
import os
from bottle import route, run, get
import time
import urllib
import urllib2
import socket
import re
import subprocess
import shlex
from ConfigParser import SafeConfigParser
from time import sleep

config_file = "/etc/pingnaut/config.json"
if os.path.isfile(config_file) == True:
    with open(config_file) as data_file:
        config = json.load(data_file)
else:
    sys.exit("ERROR: no config file %s found!" % config_file)

debug = 'F'
statname = "pingnaut-consumer-%s" % config['region']
statport = "18002"

def bug(msg):
        if debug == 'T':
                print "DEBUG: %s" % msg


t = time.localtime()
ts = time.strftime('%Y-%m-%dT%H:%M:%S%Z', t)
rootdir = "/opt/megaphone"

# Change working directory so relative paths (and template lookup) work again
root = os.path.join(os.path.dirname(__file__))
sys.path.insert(0, root)

def runcom(command_line):
        process = subprocess.Popen(shlex.split(command_line), stdout = subprocess.PIPE, stderr = subprocess.PIPE)
        out, error = process.communicate()
        return out

def listsearch(string, list):
	result = []
	for l in list:
		s = re.search(string, l)
		if s != None:
			result.append(l)
	return result

def test(command, search, count):
	result = 0
	t = runcom(command).split('\n')
	c = listsearch(search, t)
	if len(c) < count:
		result = 1
	return result
	

# generate nested python dictionaries, copied from here:
# http://stackoverflow.com/questions/635483/what-is-the-best-way-to-implement-nested-dictionaries-in-python
class AutoVivification(dict):
        """Implementation of perl's autovivification feature."""
        def __getitem__(self, item):
                try:
                        return dict.__getitem__(self, item)
                except KeyError:
                        value = self[item] = type(self)()
                        return value
def tests():
	result = { "status": "OK", "message": "Everything is OK!" }
	msg = []
	bug("checking for processes")
	r = test("ps awux", "consumer.py", 1)
	if r > 0:
		msg.append("Not enough process found!")
	if len(msg) > 0:
		message = ""
		result["status"] = "Critical"
		for m in msg:
			message += "%s," % m
		result["message"] = message[:-1]
	return result
		
@get('/status')
def status():
	result = tests()
	data = AutoVivification()
	data['id'] = statname
	data['status'] = result["status"]
	data['date'] = ts
	data['message'] = result["message"]
	return data
sleep(15)
run(host='0.0.0.0', port=statport, debug=True)
